📑 Sort bottom dialog
Software-Meister-High-School-Community/MOIZA_Android pull request #27
Opened 2022-03-02 23:12 UTC by leehyeonbin

게시물 화면 정렬 버튼 클릭시 다이얼로그 추가

2022-03-02 23:14 UTC, leehyeonbin commented
이미지 수정할게요...

2022-03-02 23:33 UTC, 100Seung-Min approved these changes
good

2022-03-04 00:50 UTC, aahspringaa4 commented
주석은 커밋 안하시는게 보통 좋아요. 해결 하시거나 지우는게 나을듯 합니다.

2022-03-04 00:51 UTC, aahspringaa4 commented
띄워쓰기같은 코드 스타일은 전체적으로 맞춰주시는것이 좋습니다. control comand L 눌러서 줄바꿈도 신경써주세요.

2022-03-04 00:52 UTC, aahspringaa4 commented
xml의 id들이 너무 알아 보기 힘들게 짜주신것 같습니다. 다른 사람이 봤을때도 보기 편하게 id를 지정해주시는 것이 좋을 것 같습니다.

2022-03-04 00:54 UTC, aahspringaa4 commented
가이드 라인을 쓰지 않아도 될 곳에서도 가이드라인을 너무 쓸데없이 많이 사용하신것 같습니다. 너무 과도한 가이드 라인은 xml 오류를 불러 올 수도 있습니다.

2022-03-04 00:54 UTC, aahspringaa4 commented
불필요한 두줄 띄워쓰기도 정리해주시면 좋을 것 같습니다.

2022-03-04 00:55 UTC, aahspringaa4 commented on app/src/main/res/values/strings.xml
> +    <string name="all_delete">전체삭제</string>
여기서도 띄워쓰기가 너무 불규칙적입니다. moiza는 오픈 소스 이기 때문에 코드는 클린 하게 짜는게 프로젝트 이미지상 좋을 것같습니다.

2022-03-04 02:03 UTC, limsaehyun requested changes
전체적으로 틀은 잘 잡힌 것 같아.
그런데 불필요한 코드나 띄어쓰기 import코드들은 다 제거해줘
그리고 XML이랑 코드들 코드 정리 단축키로 정리 해주면 좋을 것 같아
그리고 view id는 규칙에 따라서 lowerCamelCase로 해야 할 것 같아

2022-03-04 02:03 UTC, limsaehyun commented on app/src/main/java/com/moizaandroid/moiza/ui/component/category/CategoryFragment.kt
> +//    fun categoryBtn(view: View) {
주석 코드는 지워줘

2022-03-04 02:03 UTC, limsaehyun commented on app/src/main/java/com/moizaandroid/moiza/ui/component/board/dialog/PostDialog.kt
> +    companion object {
로그 찍을 때 사용하는 TAG라면 다 지워줘

2022-03-04 02:03 UTC, limsaehyun commented on app/src/main/res/layout/fragment_recent_search.xml
> +            android:id="@+id/recent_search_rv"
view 네이밍은 전부 lowerCamelCase로 부탁해

2022-03-04 02:03 UTC, limsaehyun commented on app/src/main/java/com/moizaandroid/moiza/ui/component/category/CategoryFragment.kt
> +        Log.d(TAG, "click category")
로그 코드는 전부 지워주면 좋을 것 같아

2022-03-05 07:44 UTC, leehyeonbin commented on app/src/main/java/com/moizaandroid/moiza/ui/component/category/CategoryFragment.kt
> +//    fun categoryBtn(view: View) {
체크

2022-03-05 07:44 UTC, leehyeonbin commented on app/src/main/java/com/moizaandroid/moiza/ui/component/board/dialog/PostDialog.kt
> +    companion object {
오케이

2022-03-05 07:45 UTC, leehyeonbin commented on app/src/main/res/layout/fragment_recent_search.xml
> +            android:id="@+id/recent_search_rv"
오케이

2022-03-05 07:45 UTC, leehyeonbin commented on app/src/main/java/com/moizaandroid/moiza/ui/component/category/CategoryFragment.kt
> +        Log.d(TAG, "click category")
확인

2022-03-07 00:16 UTC, limsaehyun approved these changes
잘했어 지금 pr 단위가 너무 커서 단위를 좀 좁혀주면 좋을 것 같아

2022-03-07 00:25 UTC, leehyeonbin commented
오케이...ㅎ 바로바로 해줄게

2022-03-07 00:25 UTC, merged